#!/usr/bin/env bash

# Vérifie si un argument est passé
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}" >&2
    exit 1
fi

# Assigne l'argument à une variable
IP_ADDRESS="$1"

# Pinge l'adresse IP 5 fois
ping -c 5 "$IP_ADDRESS"
